### ISSUE TITLE
iOS 13 Not Working

### ISSUE THREAD

**Issue by ChristopherJohnson25** [milk-and-cookies-io/react-native-haptic-feedback#39]
This does not seem to be working on iOS 13, has anyone been experiencing the same issues?

**Comment by mkuczera** [comment]
Hi there, so far i didn´t notice any issues. Is there any Error and/or Warning inside XCode to provide more informations?

**Comment by ChristopherJohnson25** [comment]
Yes, I just tested again, it does work! However, for some reason it's not getting fired on React Native Swiper actions. More than likely a problem with that, thanks!

**Comment by ChristopherJohnson25** [comment]
On second thought, do you mind confirming the usage of this? 

I'm not able to get this to work on any action (I come from Ember land, so not sure if correct).

See code here, 


```
click(){
    ReactNativeHapticFeedback.trigger("selection");
}

<Button onPress={() => this.click()}>Selection Vibrate</Button>
```

**Comment by mkuczera** [comment]
Hi, sorry for the late response. this seems actually fine. Is there anything popping up as a warning? Note: the real haptic feedback on iOS is only available on iPhone 6s and up. Anything else needs to fall back to a vibrate. To enable this, just pass in the second argument as true

**Comment by joseguya** [comment]
@mkuczera Having issues with ios 13 too with a warning: 

> RNReactNativeHapticFeedback is not available

With not much else

**Comment by ChristopherJohnson25** [comment]
It's odd, it seems to work in some functions, and not in others. I'm new to React Native, so it could be user error.

**Comment by joseguya** [comment]
I managed to log the error: 

`TypeError: Cannot read property 'trigger' of undefined
    at Function.RNReactNativeHapticFeedback.trigger (index.js:13)`

At index.js of the package

**Comment by pie6k** [comment]
I've got the same issue,

I'm unsing React Native `0.61.2`, I'm also using autolink feature with `use_native_modules!` inside `Podfile`

Calling trigger results in `RNReactNativeHapticFeedback is not available`

![image](https://user-images.githubusercontent.com/7311462/67373551-219bfa00-f580-11e9-821c-e430cd5dabf9.png).

**Comment by mkuczera** [comment]
Hi, i will have a look on this after the weekend. In the meantime: Is the Haptic Feedback Package in the pod install logs?

**Comment by joseguya** [comment]
> Hi, i will have a look on this after the weekend. In the meantime: Is the Haptic Feedback Package in the pod install logs?

I finally made It work, and it was my mistake. The package was only set on one target and not in the one I was using at the moment. Working great now.

**Comment by dnosk** [comment]
Hi! I'm still getting this message

"react-native": "0.61.5",
"react-native-haptic-feedback": "^1.8.2",

**Comment by johnlim5847** [comment]
@dnosk Hi did you find any solution for this?

**Comment by dnosk** [comment]
I ended up writing it in Swift :/

**Comment by mkuczera** [comment]
Hi, i still can´t reproduce the issue. Do you guys have any repo project available?
Also: 
- Did pod install output any warnings/errors regarding haptic-feedback and/or iOS Deployment targets?
- Is the haptic feedback package included in the Podfile.lock?

**Comment by felix-voicehub** [comment]
Had the same issue, but a clean build solved it.

**Comment by Nicolaayip** [comment]
Got same error, solved by manual linking with
`npm link react-native-haptic-feedback && cd ios && pod install`

**Comment by ebarahona** [comment]
Check your imports use: 
`import ReactNativeHapticFeedback from 'react-native-haptic-feedback'; `
