### ISSUE TITLE
Not working with react native 0.61.5

### ISSUE THREAD

**Issue by johnlim5847** [milk-and-cookies-io/react-native-haptic-feedback#40]
Hi,
I just installed on my new react native project. I have cd to `pod` to install as well but I'm having this warning at below

![Screenshot 2019-12-05 at 12 02 22 PM](https://user-images.githubusercontent.com/3675946/70203210-20e9ac80-1757-11ea-833c-6f85722ccd08.png)

do you have any solution for that?

```
react-native-haptic-feedback : ^1.8.2
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 27.80 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by johnlim5847** [comment]
Found the solution.

For some reason, it doesn't add to my libPod file so I manually added it in `Link binary With libraries` under Build phases

**Comment by johnlim5847** [comment]
The `libRNReactNativeHapticFeedback.a` didn't add to my `libPods` file of my project so I manually added it in `Link Binary with Libraries` under `Build Phases` it works like a charm now thanks :)

**Comment by NikitaNeganov** [comment]
@johnlim5847 Did you `link` the package initially with `react-native link`?

**Comment by FlawaCLV** [comment]
Still experiencing this issue. @johnlim5847 what was your solution ?
